language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:travis"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - jruby-head
  - ruby-head
disabled:
  - rbx-19mode
notifications:
  email:
    recipients:
      - arne@arnebrasseur.net
    on_success: never
    on_failure: change
