---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
    - Hexp::Builder#initialize
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude: []
  max_calls: 2
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
    - Hexp::List#initialize
    - Hexp::Node::Domize#set_attributes
    - Hexp::Node::Normalize#children
    - Hexp::Node::Normalize#normalized_children
    - Hexp::Node::PP#pp_attributes
    - Hexp::Node::PP#pp_children
    - Hexp::Node#rewrite_children
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude: []
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude: []
  max_allowed_nesting: 2
  ignore_iterators:
    - any?
NilCheck:
  enabled: true
  exclude:
    - Hexp::Node#rewrite
    - Hexp::Node#set_attr
RepeatedConditional:
  enabled: true
  exclude:
    - Hexp::Builder
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude: []
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
    - Hexp::Node
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
    - each
    - Hexp::Node#rewrite
    - Hexp::Node::Normalize#normalized_children
    - Hexp::Builder#tag!
  max_statements: 5
UncommunicativeMethodName:
  enabled: true
  exclude:
    - Hexp#self.Array
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude:
    - Hexp::TextNode#class?
UtilityFunction:
  enabled: true
  exclude:
    - Hexp::List#initialize
    - Hexp::Node::Domize#set_attributes
    - Hexp::TextNode#attributes
    - Hexp::TextNode#children
  max_helper_calls: 0
